### ISSUE TITLE
Failed to attach pdfs

### ISSUE THREAD

**Issue by gwharton** [fooman/emailattachments-m2#5]
Module version 2.0.8
Magento 2.2.3

Under certain circumstances, pdfs are not attached to emails.
I have two third party modules that provide additional mass actions to the sales_order_grid that allow you to "Resend invoice Email".

One of the modules works properly and attaches the pdf to the email that is sent.
The other modules emails do not have pdf's attached.

On further inspection,

The fooman module overrides the following in di.xml

\Magento\Sales\Model\Order\Email\Sender\InvoiceSender
\Magento\Sales\Model\Order\Email\Sender\InvoiceCommentSender
\Magento\Sales\Model\Order\Email\Sender\ShipmentSender
\Magento\Sales\Model\Order\Email\Sender\ShipmentCommentSender
\Magento\Sales\Model\Order\Email\Sender\CreditmemoSender
\Magento\Sales\Model\Order\Email\Sender\CreditmemoCommentSender

However the module fails to override the following, which can also be used to send emails (the module that fails uses these methods)

\Magento\Sales\Model\Order\Invoice\Sender\EmailSender
\Magento\Sales\Model\Order\Shipment\Sender\EmailSender
\Magento\Sales\Model\Order\Creditmemo\Sender\EmailSender

Overrides for these need adding, which fire the appropriate fooman event to attach the pdfs.

**Comment by amenk** [comment]
Same happens when you use the salesShipOrder (POST /V1/order/{orderId}/ship) API.

I suggest also to refactor the core :-) https://github.com/magento/magento2/issues/14885

**Comment by amenk** [comment]
@gwharton Did you already work on a pull request for this, otherwise I might have to do it :-)

**Comment by amenk** [comment]
@gwharton here is a partly fix, feel free to test. Maybe you can implement the other other missing observers using the same way, if you have a time. I only need it for shipments for now :-)

**Comment by amenk** [comment]
@gwharton I added the invoice + creditmemo provisionally - I do not use those APIs, maybe you can have a look with testing?

**Comment by gwharton** [comment]
@amenk That looks great. I've added a couple of comments to the commit. 

Its pretty much identical to my local fix, other than that when I try to dispatch the event using $this->eventManager->dispatch it results in the function exiting immediately for some reason. It never gets to the return parent::send line.

In my local copy, I instantiated a copy of the object manager, used that to instantiate a copy of the event manager and then dispatched from there, which worked correctly.

I couldnt for the life of me figure out why dispatching using $this->eventManager->dispatch would make it crash. This is why I moved on, and why I didnt put myself up to doing a pull request, as using object manager like this, I believe, is not the right way.

I'll try grabbing your repo and installing it on my test server. I'd be interested if I run into the same problems I did during my testing.

**Comment by amenk** [comment]
:-) Thanks for reviewing

**Comment by fooman** [comment]
Thanks all for your feedback and participating here. I am currently looking into this. To confirm to be able to replicate the issue with default Magento one would need to use an API request like salesShipOrder?

**Comment by gwharton** [comment]
Yeahh, I dont think there are any builtin operations that use the \Magento\Sales\Model\Order\Invoice\Sender\EmailSender etc functions, but they are not marked as deprecated and several third party modules do use them.

Its probably not too difficult to knock up a module that triggers of an email using these methods for testing purposes. Let me know if you would like me to generate one that can be used.

**Comment by fooman** [comment]
Thanks for confirming @gwharton 

If you wouldn't mind testing out the changes that I am making a preview of the new version is up on 
https://github.com/fooman/emailattachments-implementation-m2 - develop branch

(this is also where this repo will mostly live going forward, this repo will be reduced to metapackage - more on that [here](https://store.fooman.co.nz/blog/improved-versioning-for-magento-2-extensions.html))

**Comment by gwharton** [comment]
No worries. I'll take a look at this today.

P.S. What is your method of checking out the code from github and having it in your Magento tree for testing. Because the code is in the "src" folder, it is stopping me from checking out directly into app/code/Fooman/EmailAttachments as I end up with app/code/Fooman/EmailAttachments/src. What is your method?

**Comment by fooman** [comment]
Thanks - I just added it to packagist so for now
`composer require fooman/emailattachments-implementation-m2:dev-develop` should do the trick.

**Comment by gwharton** [comment]
Ahh, what I was hoping to do was add it as a submodule to my private github repo.

git submodule add https://github.com/fooman/emailattachments-implementation-m2 app/code/Fooman/EmailAttachment

**Comment by gwharton** [comment]
Version 104.0.0 Seems to work just fine on all my test cases. It also fixes the old issue I raised, but closed because I didnt use the functionality (https://github.com/fooman/emailattachments-m2/issues/4)

Operation | Version 2.1.0 | Version 104.0.0
-- | -- | --
Credit Memo   -> Send Email (Bcc) | PASS | PASS
Credit Memo   -> Send Email (Separate Email - Customer) | PASS | PASS
Credit Memo   -> Send Email (Separate Email - Admin) | FAILED | PASS
Invoice ->   Send Email (Bcc) | PASS | PASS
Invoice ->   Send Email (Separate Email - Customer) | PASS | PASS
Invoice ->   Send Email (Separate Email - Admin) | FAILED | PASS
Resend invoice   email (Mageworx orders grid) (Bcc) | FAILED | PASS
Resend invoice   email (Mageworx orders grid) (Separate Email - Customer) | FAILED | PASS
Resend invoice   email (Mageworx orders grid) (Separate Email - Admin) | FAILED | PASS
Invoice   (Notify) (Mageworx orders grid) (Bcc) | FAILED | PASS
Invoice   (Notify) (Mageworx orders grid) (Separate Email - Customer) | FAILED | PASS
Invoice   (Notify) (Mageworx orders grid) (Separate Email - Admin) | FAILED | PASS
Invoice   (Notify) (Xtento Simplify Bulk Order Processing) (Bcc) | PASS | PASS
Invoice   (Notify) (Xtento Simplify Bulk Order Processing) (Separate Email - Customer) | PASS | PASS
Invoice   (Notify) (Xtento Simplify Bulk Order Processing) (Separate Email - Admin) | FAILED | PASS
